spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ArtGallery
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  aop:
    proxy-target-class: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

